1. Create a numpy array of size 2 x 2

In [1]:
import numpy as np

In [2]:
n1 = np.array([[1,2],[3,4]])
print(n1)

[[1 2]
 [3 4]]


2. Create a random numpy array of size 3 x 4

In [3]:
n2 = np.random.random((3,4))
print(n2)

[[0.76541052 0.71847552 0.48594157 0.7650053 ]
 [0.44847818 0.92508574 0.99082255 0.30018577]
 [0.15587831 0.86912326 0.47633151 0.99318733]]


3. Create a numpy array of ones and a numpy array of zeroes

In [4]:
n3a = np.ones((2,2))
print(n3a)

n3b = np.zeros((2,2))
print('\n',n3b)


[[1. 1.]
 [1. 1.]]

 [[0. 0.]
 [0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [5]:
n4a = np.random.random((6,3))
print('A random numpy array: \n')
print(n4a)


n4b = n4a.T
print('\nTransposed numpy array: \n')
print(n4b)


A random numpy array: 

[[0.14529536 0.64977927 0.99236089]
 [0.57311506 0.81538504 0.4078672 ]
 [0.65653662 0.49278117 0.40599592]
 [0.65123406 0.6217588  0.36431739]
 [0.94481533 0.53888341 0.52769777]
 [0.43931614 0.98509157 0.1276554 ]]

Transposed numpy array: 

[[0.14529536 0.57311506 0.65653662 0.65123406 0.94481533 0.43931614]
 [0.64977927 0.81538504 0.49278117 0.6217588  0.53888341 0.98509157]
 [0.99236089 0.4078672  0.40599592 0.36431739 0.52769777 0.1276554 ]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [6]:
n=3
p=5
m=4

n5a = np.random.random((n,p))
n5b = np.random.random((p,m))

n5c = np.dot(n5a, n5b)

print('First numpy array: \n\n', n5a)
print('\nSecond numpy array: \n\n', n5b)
print('\nThe dot product: \n\n', n5c)


First numpy array: 

 [[0.08993647 0.35759162 0.35805158 0.97018677 0.84996736]
 [0.01995816 0.24795366 0.68378545 0.30918184 0.18924629]
 [0.47694771 0.5045623  0.10928125 0.1658944  0.59465236]]

Second numpy array: 

 [[0.11366601 0.11466411 0.94868964 0.0082502 ]
 [0.3204549  0.40473361 0.14214778 0.69108442]
 [0.46202809 0.37309874 0.55473957 0.32685828]
 [0.11333366 0.6434227  0.05113019 0.73038401]
 [0.04112702 0.42790963 0.15264232 0.15233709]]

The dot product: 

 [[0.43515604 1.27657984 0.51412485 1.20299056]
 [0.44047846 0.63767808 0.47819853 0.6496732 ]
 [0.30965091 0.66087249 0.68407172 0.60010376]]
