<a href="https://colab.research.google.com/github/25005517-code/data_science_w3/blob/main/WIX1007_Tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a numpy array of size 2 x 2

In [1]:
import numpy as np

In [2]:
n1 = np.array([[1,2],[3,4]])
print(n1)

[[1 2]
 [3 4]]


2. Create a random numpy array of size 3 x 4

In [3]:
n2 = np.random.random((3,4))
print(n2)

[[0.29894486 0.98470363 0.71508266 0.86612257]
 [0.76327359 0.69270204 0.81255163 0.38923423]
 [0.91237754 0.66791527 0.44074426 0.24288905]]


3. Create a numpy array of ones and a numpy array of zeroes

In [4]:
n3a = np.ones((2,2))
print(n3a)

[[1. 1.]
 [1. 1.]]


In [5]:
n3b = np.zeros((2,2))
print(n3b)

[[0. 0.]
 [0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [6]:
n4a = np.random.random((6,3))
print('A random numpy array: \n')
print(n4a)

A random numpy array: 

[[0.47627197 0.07409374 0.44903015]
 [0.44800226 0.5280461  0.84182958]
 [0.03856703 0.97740639 0.48996383]
 [0.48055424 0.92316574 0.71594296]
 [0.67227099 0.30152424 0.09639837]
 [0.0950794  0.49077061 0.06232489]]


In [7]:
n4b = n4a.T
print('\n\nTransposed numpy array: \n')
print(n4b)



Transposed numpy array: 

[[0.47627197 0.44800226 0.03856703 0.48055424 0.67227099 0.0950794 ]
 [0.07409374 0.5280461  0.97740639 0.92316574 0.30152424 0.49077061]
 [0.44903015 0.84182958 0.48996383 0.71594296 0.09639837 0.06232489]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [8]:
n=3
p=5
m=4

n5a = np.random.random((n,p))
n5b = np.random.random((p,m))

n5c = np.dot(n5a, n5b)

print('First numpy array: \n\n', n5a)
print('\nSecond numpy array: \n\n', n5b)
print('\nThe dot product: \n\n', n5c)

First numpy array: 

 [[0.55769181 0.80081495 0.40058591 0.016178   0.06214013]
 [0.64192354 0.35829904 0.70482719 0.3629546  0.27104572]
 [0.26923522 0.94253328 0.82122752 0.69830347 0.0878951 ]]

Second numpy array: 

 [[0.8931291  0.58551861 0.9420662  0.3192693 ]
 [0.02885357 0.59748394 0.46049098 0.71978805]
 [0.41035682 0.85393291 0.97045372 0.28757009]
 [0.10156767 0.12712754 0.84171114 0.02419578]
 [0.97904003 0.92972215 0.78398555 0.71108496]]

The dot product: 

 [[0.74806115 1.20691622 1.34523492 0.91424578]
 [1.17511851 1.48994997 1.97172898 0.86705157]
 [0.76163145 1.59255556 2.14130708 1.07994009]]


#Part 2-Colab and github
1. From Google Colab, push the notebook onto your GitHub

In [ ]:
#connect to google drive
from google.colab import drive
drive.mount('/content/drive')

#move to google drive
%cd /content/drive/MyDrive

#create a git repos folder and move into it
!mkdir -p git_repos
%cd git_repos